#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# from https://en.wikipedia.org/wiki/List_of_seas
waters = [
"Davis Strait",
"Labrador Sea",
"Gulf of St. Lawrence",
"Gulf of Maine",
"Bay of Fundy",
"Massachusetts Bay",
"Cape Cod Bay",
"Nantucket Sound",
"Buzzards Bay",
"Narragansett Bay",
"Long Island Sound",
"New York Bay",
"Chesapeake Bay",
"Gulf of Mexico",
"Bay of Campeche",
"Campeche Bank",
"Caribbean Sea",
"Gulf of Gonve ",
"Gulf of Honduras",
"Golfo de los Mosquitos",
"Gulf of Venezuela",
"Gulf of Paria",
"Gulf of Darién",
"Argentine Sea",
"Norwegian Sea",
"North Sea",
"Wadden Sea",
"Baltic Sea",
"Archipelago Sea",
"Bothnian Sea",
"Central Baltic Sea",
"Gulf of Riga",
"Oresund Strait",
"Sea of Åland",
"English Channel",
"Celtic Sea",
"Bay of Biscay",
"Cantabric Sea",
"Mediterranean Sea",
"Adriatic Sea",
"Aegean Sea",
"Myrtoan Sea",
"Sea of Crete",
"Thracian Sea",
"Alboran Sea",
"Balearic Sea",
"Catalan Sea",
"Cilician Sea",
"Gulf of Sidra",
"Ionian Sea",
"Levantine Sea",
"Libyan Sea",
"Ligurian Sea",
"Sea of Sardinia",
"Sea of Sicily",
"Tyrrhenian Sea",
"Marmara Sea",
"Black Sea",
"Sea of Azov",
"Gulf of Guinea",
"Chukchi Sea",
"East Siberian Sea",
"Laptev Sea",
"Kara Sea",
"Barents Sea",
"Pechora Sea",
"White Sea",
"Wandel Sea",
"Greenland Sea",
"Lincoln Sea",
"Baffin Bay",
"The Northwest Passages",
"Amundsen Gulf",
"Hudson Strait",
"Hudson Bay",
"James Bay",
"Beaufort Sea",
"Amundsen Sea",
"Bass Strait",
"Bellingshausen Sea",
"Cooperation Sea",
"Cosmonauts Sea",
"Davis Sea",
"D'Urville Sea",
"Drake Passage",
"Great Australian Bight",
"Gulf St Vincent",
"King Haakon VII Sea",
"Lazarev Sea",
"Mawson Sea",
"Riiser-Larsen Sea",
"Ross Sea",
"Scotia Sea",
"Somov Sea",
"Spencer Gulf",
"Weddell Sea",
"Andaman Sea",
"Arabian Sea",
"Bay of Bengal",
"Gulf of Aden",
"Gulf of Oman",
"Laccadive Sea",
"Mozambique Channel",
"Persian Gulf",
"Red Sea",
"Timor Sea",
"Arafura Sea",
"Bali Sea",
"Banda Sea",
"Bering Sea",
"Bismarck Sea",
"Bohai Sea",
"Bohol Sea",
"Camotes Sea",
"Celebes Sea",
"Ceram Sea",
"Chilean Sea",
"Sea of Chiloé",
"Coral Sea",
"East China Sea",
"Flores Sea",
"Gulf of Alaska",
"Gulf of California",
"Gulf of Carpentaria",
"Gulf of Thailand",
"Halmahera Sea",
"Java Sea",
"Koro Sea",
"Mar de Grau",
"Molucca Sea",
"Philippine Sea",
"Salish Sea",
"Savu Sea",
"Sea of Japan",
"Sea of Okhotsk",
"Seto Inland Sea",
"Sibuyan Sea",
"Solomon Sea",
"South China Sea",
"Sulu Sea",
"Tasman Sea",
"Visayan Sea",
"Yellow Sea",
]
