caspian_sea = [
"Labrador Sea",
"Caribbean Sea",
"Norwegian Sea",
"Cantabric Sea",
"Adriatic Sea",
"Alboran Sea",
"Balearic Sea",
"Catalan Sea",
"Cilician Sea",
"Ligurian Sea",
"Tyrrhenian Sea",
"Marmara Sea",
"Pechora Sea",
"Amundsen Sea",
"Cosmonauts Sea",
"D'Urville Sea",
"Lazarev Sea",
"Andaman Sea",
"Arabian Sea",
"Camotes Sea",
"Celebes Sea",
"East China Sea",
"Molucca Sea",
"Solomon Sea",
"South China Sea",
]
